-- CreateTable
CREATE TABLE "LaboratorioAC" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "laboratoryname" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
